// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  education: dynamic(() => import("./Education")),
  experience: dynamic(() => import("./Experience")),
  hero: dynamic(() => import("./Hero")),
  projects: dynamic(() => import("./Projects")),
  skills: dynamic(() => import("./Skills")),
};
